name: Publish Package to npmjs
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - name: install pnpm
        uses: pnpm/action-setup@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: '20.x'
      - run: pnpm install
      - run: pnpm eslint
      - name: set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: pnpm publish --provenance --access public
        env:
          npm_config__authtoken: ${{ secrets.NPM_TOKEN }}
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
